### PR TITLE
Flutter client

### PR DESCRIPTION
**Pull request by DariusPrimarius**
I made it !

Now flutter client displays new contacts, messages send and received in real time without need to refresh widget manually. However it still displays all the users messages in one chat window (same as android client does). 

Future PR will include :
- keeping messages from different users in apart windows (just quick fix with array)
- option for blocking choosen user (in case of spam etc.)

Untitled

### CODE REVIEW

**Comment by DariusPrimarius** [comment]
Update. Users now are separated, also formating included. 
Screenshot_1704925748

**Review by tvd12 — APPROVED** [review]
LGTM

**Comment by tvd12** [comment]
@DariusPrimarius pls resolve the conflict

**Comment by DariusPrimarius** [comment]
In fact for this to run the chat user needs only 3 files  (main, socket_proxy.dart, chat.dart) where main is login screen so in fact 2 files. Rest is cloned from [this](https://github.com/youngmonkeys/ezyfox-server-flutter-client) repo. With next update I'm going to remove unnecessary files and include installation manual in README.md

**Pull request merged**
